### ISSUE TITLE
Limit on password length argument integer

### ISSUE THREAD

**Issue by m33k** [m33k/passwd_gen#1]
The random library appears to have a limit of how many characters it can make random for you. 

We'll need a condition that checks if the number is less than x then continue else exit.

```
python3 passwd_gen.py 90
Traceback (most recent call last):
  File "passwd_gen.py", line 16, in <module>
    passwd = random.sample(string, inputs['integers'])
  File "/usr/lib64/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
```

**Comment by m33k** [comment]
The limit is 63. Anything below 63 the random library doesn't have an issue with. The code in commit: https://github.com/m33k/passwd_gen/commit/087cc9f6ef0dbf12860fe9001003fe329110110e will gracefully exit if the length is greater than 62.

Marking this as resolved.
